packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
  - prisma
  - lefthook
  - sharp

patchedDependencies:
  '@nuxt/test-utils@4.0.0': patches/@nuxt__test-utils@4.0.0.patch
