export interface PerfFieldDef {
  identifier: string;
  name: string;
  type:
    | 'ENTRY_TITLE'
    | 'SLUG'
    | 'TEXT'
    | 'TEXTAREA'
    | 'RICHTEXT'
    | 'DATETIME'
    | 'RELATION';
  required?: boolean;
  options?: Record<string, unknown>;
}

export interface PerfContentTypeDef {
  identifier: string;
  name: string;
  description: string;
  fields: PerfFieldDef[];
}

export const PERF_CONTENT_TYPES: PerfContentTypeDef[] = [
  {
    identifier: 'PerfAuthor',
    name: 'Perf Author',
    description: 'Generated by @boject/perf. Safe to delete outside perf runs.',
    fields: [
      { identifier: 'name', name: 'Name', type: 'ENTRY_TITLE', required: true },
      { identifier: 'bio', name: 'Bio', type: 'TEXTAREA' },
    ],
  },
  {
    identifier: 'PerfArticle',
    name: 'Perf Article',
    description: 'Generated by @boject/perf. Safe to delete outside perf runs.',
    fields: [
      {
        identifier: 'title',
        name: 'Title',
        type: 'ENTRY_TITLE',
        required: true,
      },
      { identifier: 'slug', name: 'Slug', type: 'SLUG' },
      { identifier: 'excerpt', name: 'Excerpt', type: 'TEXT' },
      { identifier: 'body', name: 'Body', type: 'RICHTEXT' },
      { identifier: 'publishDate', name: 'Publish Date', type: 'DATETIME' },
      {
        identifier: 'author',
        name: 'Author',
        type: 'RELATION',
        options: { targetContentTypeIdentifiers: ['PerfAuthor'] },
      },
    ],
  },
];
