import type { Bundle } from '@boject/cli/vendor/contentBundleTypes';
import { FIELD_TYPES } from '@boject/cli/vendor/fieldTypes';

/**
 * Hardcoded PerfArticle + PerfAuthor as a Bundle. The workspace's
 * `pnpm perf:sweep` flow passes this to `generatePerfData` to keep its
 * row counts and field shape unchanged from the pre-#159 seed.
 *
 * IDs are valid UUIDs (deterministic, in the unused 01900000-xxxx-4xxx-8xxx
 * range so they can never collide with real Prisma-generated v4s). Required
 * because /api/content-entries POST validates contentTypeId against a UUID
 * regex — a non-UUID string would 400.
 */
export const PERF_BUNDLE: Bundle = {
  version: 2,
  exportedAt: '2026-05-07T00:00:00.000Z',
  portable: false,
  contentTypes: [
    {
      id: '01900000-0000-4000-8000-00000000a001',
      identifier: 'PerfAuthor',
      name: 'Perf Author',
      description:
        'Generated by @boject/perf. Safe to delete outside perf runs.',
      fields: [
        {
          id: '01900000-0000-4000-8000-00000000a101',
          identifier: 'name',
          name: 'Name',
          type: FIELD_TYPES.ENTRY_TITLE,
          required: true,
          unique: true,
          order: 0,
          options: null,
        },
        {
          id: '01900000-0000-4000-8000-00000000a102',
          identifier: 'bio',
          name: 'Bio',
          type: FIELD_TYPES.TEXTAREA,
          required: false,
          order: 1,
          options: null,
        },
      ],
    },
    {
      id: '01900000-0000-4000-8000-00000000a002',
      identifier: 'PerfArticle',
      name: 'Perf Article',
      description:
        'Generated by @boject/perf. Safe to delete outside perf runs.',
      fields: [
        {
          id: '01900000-0000-4000-8000-00000000a201',
          identifier: 'title',
          name: 'Title',
          type: FIELD_TYPES.ENTRY_TITLE,
          required: true,
          unique: true,
          order: 0,
          options: null,
        },
        {
          id: '01900000-0000-4000-8000-00000000a202',
          identifier: 'slug',
          name: 'Slug',
          type: FIELD_TYPES.SLUG,
          required: false,
          unique: true,
          order: 1,
          options: null,
        },
        {
          id: '01900000-0000-4000-8000-00000000a203',
          identifier: 'excerpt',
          name: 'Excerpt',
          type: FIELD_TYPES.TEXT,
          required: false,
          order: 2,
          options: null,
        },
        {
          id: '01900000-0000-4000-8000-00000000a204',
          identifier: 'body',
          name: 'Body',
          type: FIELD_TYPES.RICHTEXT,
          required: false,
          order: 3,
          options: null,
        },
        {
          id: '01900000-0000-4000-8000-00000000a205',
          identifier: 'publishDate',
          name: 'Publish Date',
          type: FIELD_TYPES.DATETIME,
          required: false,
          order: 4,
          options: null,
        },
        {
          id: '01900000-0000-4000-8000-00000000a206',
          identifier: 'author',
          name: 'Author',
          type: FIELD_TYPES.RELATION,
          required: false,
          order: 5,
          options: {
            targetContentTypeIds: ['01900000-0000-4000-8000-00000000a001'],
          },
        },
      ],
    },
  ],
};
