import type { Bundle } from '@boject/cli/vendor/contentBundleTypes';

/**
 * Hardcoded PerfArticle + PerfAuthor as a Bundle. The workspace's
 * `pnpm perf:sweep` flow passes this to `generatePerfData` to keep its
 * row counts and field shape unchanged from the pre-#159 seed.
 */
export const PERF_BUNDLE: Bundle = {
  version: 2,
  exportedAt: '2026-05-07T00:00:00.000Z',
  portable: false,
  contentTypes: [
    {
      id: 'ct-perf-author',
      identifier: 'PerfAuthor',
      name: 'Perf Author',
      description:
        'Generated by @boject/perf. Safe to delete outside perf runs.',
      fields: [
        {
          id: 'pa1',
          identifier: 'name',
          name: 'Name',
          type: 'ENTRY_TITLE',
          required: true,
          unique: true,
          order: 0,
          options: null,
        },
        {
          id: 'pa2',
          identifier: 'bio',
          name: 'Bio',
          type: 'TEXTAREA',
          required: false,
          order: 1,
          options: null,
        },
      ],
    },
    {
      id: 'ct-perf-article',
      identifier: 'PerfArticle',
      name: 'Perf Article',
      description:
        'Generated by @boject/perf. Safe to delete outside perf runs.',
      fields: [
        {
          id: 'par1',
          identifier: 'title',
          name: 'Title',
          type: 'ENTRY_TITLE',
          required: true,
          unique: true,
          order: 0,
          options: null,
        },
        {
          id: 'par2',
          identifier: 'slug',
          name: 'Slug',
          type: 'SLUG',
          required: false,
          unique: true,
          order: 1,
          options: null,
        },
        {
          id: 'par3',
          identifier: 'excerpt',
          name: 'Excerpt',
          type: 'TEXT',
          required: false,
          order: 2,
          options: null,
        },
        {
          id: 'par4',
          identifier: 'body',
          name: 'Body',
          type: 'RICHTEXT',
          required: false,
          order: 3,
          options: null,
        },
        {
          id: 'par5',
          identifier: 'publishDate',
          name: 'Publish Date',
          type: 'DATETIME',
          required: false,
          order: 4,
          options: null,
        },
        {
          id: 'par6',
          identifier: 'author',
          name: 'Author',
          type: 'RELATION',
          required: false,
          order: 5,
          options: { targetContentTypeIds: ['ct-perf-author'] },
        },
      ],
    },
  ],
};
